name: finance

services:
  pg:
    image: "postgres:16.0-alpine3.18"
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=finance-hub